# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release_dev_version

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.1]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g yarn
          yarn install
      - name: build
        run:  npm run build
      - name: package
        run: zip -r toolbox-browser-extension.zip dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest version
          files: toolbox-browser-extension.zip
          tag_name: latest
          token: ${{ secrets.DEPLOY_TOKEN }}
